### PR TITLE
175 bug queue

### LINKED ISSUE #175: 🐞 ShowCard component does not allow adding/removing to queue
Bug is originating from line 49 of `ShowCard.tsx`.
https://github.com/Thenlie/Streamability/blob/019a135c5bfa55cdc8a8e0b2ce78cc7321229b59/src/components/ShowCard.tsx#L49
The entire element is linking to the details page, not allowing buttons nested inside to be used.

### PR DESCRIPTION
**Pull request by maxh1231**
Fixed inability to add/remove movies to watch queue

Closes #175

### CODE REVIEW

File: src/components/ShowCard.tsx [hunk 1]
```diff
@@ -46,15 +46,15 @@ export default function ShowCard(props: MovieCardProps): JSX.Element {
     return (
         <>
```
Comment (Thenlie) [inline src/components/ShowCard.tsx:47]: We can remove this fragment now that we have a single container div I believe

**Review by Thenlie — APPROVED** [review]
One small comment, otherwise all good. Easier than I thought.

File: src/components/ShowCard.tsx (hunk 1 above)
Comment (maxh1231) [reply src/components/ShowCard.tsx:47]: Current setup doesn't allow it. With a JSX conditional I believe a parent element is required and for now the fragment acts as one.

Comment (Thenlie) [reply src/components/ShowCard.tsx:47]: Good point. I am thinking it would make more sense to conditionally render this component, rather than conditionally rendering the content of the card.
```ts
{details && <ShowCard />}
```
I will make a ticket for this change.
